/*
Tabla CLIENTE sin PK.
La PK se puede repetir.
*/

CREATE TABLE CLIENTE
(
	IDCLIENTE INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CORREO VARCHAR(100) NOT NULL
);
GO

INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,CORREO) VALUES(1,'ALLISON','allison@gmail.com');
GO

INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,CORREO) VALUES(1,'SABINA','sabina@gmail.com');
GO

SELECT * FROM CLIENTE;
GO




