/*
Tabla CLIENTE con PK.
La PK NO se puede repetir.
Tiene problemas fundamentales, acepta valores duplicados en DNI y CORREO.
*/

DROP TABLE CLIENTE;
GO

CREATE TABLE CLIENTE
(
	IDCLIENTE INT NOT NULL IDENTITY(100,5), -- Identificado interno
	DNI CHAR(8) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE)
);
GO

INSERT INTO CLIENTE(DNI,NOMBRE,CORREO) VALUES('12345678','ALLISON','allison@gmail.com');
GO

INSERT INTO CLIENTE(DNI,NOMBRE,CORREO) VALUES('12345678','SABINA','sabina@gmail.com');
GO

INSERT INTO CLIENTE(DNI,NOMBRE,CORREO) VALUES('12345678','KIARA','sabina@gmail.com');
GO

SELECT * FROM CLIENTE;
GO




