/*
Tabla CLIENTE con PK.
La PK NO se puede repetir.
Aplicando UNIQUE para garantiza valores unicos en laS columnas DNI y CORREO.
*/

DROP TABLE CLIENTE;
GO

CREATE TABLE CLIENTE
(
	IDCLIENTE INT NOT NULL IDENTITY(100,5), -- Identificado interno
	DNI CHAR(8) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE),
	CONSTRAINT U_CLIENTE_DNI UNIQUE(DNI),
	CONSTRAINT U_CLIENTE_CORREO UNIQUE(CORREO)
);
GO

INSERT INTO CLIENTE(DNI,NOMBRE,CORREO) VALUES('12345678','ALLISON','allison@gmail.com');
GO

-- Genera error por que el DNI no se puede repetir.
INSERT INTO CLIENTE(DNI,NOMBRE,CORREO) VALUES('12345678','SABINA','sabina@gmail.com');
GO

-- Genera error por que el CORREO no se puede repetir.
INSERT INTO CLIENTE(DNI,NOMBRE,CORREO) VALUES('87654321','KIARA','allison@gmail.com');
GO

INSERT INTO CLIENTE(DNI,NOMBRE,CORREO) VALUES('56783456','CYNTHIA','cynthia@gmail.com');
GO

SELECT * FROM CLIENTE;
GO




