/*
Tabla CLIENTE con PK.
La PK NO se puede repetir.
*/

CREATE TABLE CLIENTE
(
	IDCLIENTE INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE)
);
GO

INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,CORREO) VALUES(1,'ALLISON','allison@gmail.com');
GO

-- Este insert debe dar error por PK duplicada
INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,CORREO) VALUES(1,'SABINA','sabina@gmail.com');
GO

SELECT * FROM CLIENTE;
GO




