
-- Creacion de la tabla venta.
-- Con PK y FK.

DROP TABLE ABC..VENTA;
GO

CREATE TABLE ABC..VENTA(
	IDVENTA INT NOT NULL IDENTITY(1,1),
	IDCLIENTE INT NOT NULL,
	PRODUCTO VARCHAR(100) NOT NULL,
	PRECIO NUMERIC(8,2) NOT NULL,
	CANTIDAD INT NOT NULL,
	IMPORTE NUMERIC(8,2) NOT NULL,
	CONSTRAINT PK_VENTA PRIMARY KEY(IDVENTA),
	CONSTRAINT FK_VENTA_CLIENTE 
		FOREIGN KEY(IDCLIENTE) REFERENCES ABC..CLIENTE
);
GO

SELECT * FROM ABC..CLIENTE;
GO

-- Esta instruccion da error por que no existe el cliente 1000.
INSERT INTO ABC..VENTA(IDCLIENTE,PRODUCTO,PRECIO,CANTIDAD,IMPORTE)
VALUES(1000,'PAPAS X KG',-4.8,5,10);
GO

INSERT INTO ABC..VENTA(IDCLIENTE,PRODUCTO,PRECIO,CANTIDAD,IMPORTE)
VALUES(100,'LAPTOP',-4.8,5,10);
GO

SELECT * FROM ABC..VENTA;
GO



