
-- Creacion de la tabla venta.
-- Sin restricciones

CREATE TABLE ABC.dbo.VENTA(
	IDVENTA INT NOT NULL IDENTITY(1,1),
	IDCLIENTE INT NOT NULL,
	PRODUCTO VARCHAR(100) NOT NULL,
	PRECIO NUMERIC(8,2) NOT NULL,
	CANTIDAD INT NOT NULL,
	IMPORTE NUMERIC(8,2) NOT NULL
);
GO

INSERT INTO ABC..VENTA(IDCLIENTE,PRODUCTO,PRECIO,CANTIDAD,IMPORTE)
VALUES(1000,'PAPAS X KG',-4.8,5,10);
GO

SELECT * FROM ABC..VENTA;
GO



